# Generated by Django 4.2.5 on 2023-09-28 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlap',
            name='user',
        ),
        migrations.AddField(
            model_name='productlap',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app2.product'),
        ),
    ]
