# Generated by Django 4.2.5 on 2023-09-17 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, null=True)),
                ('brand_name', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(max_length=255, null=True)),
                ('price', models.CharField(max_length=255, null=True)),
                ('battery', models.CharField(max_length=255, null=True)),
                ('sound_quality', models.CharField(max_length=255, null=True)),
                ('size', models.CharField(max_length=255, null=True)),
                ('quantity', models.CharField(max_length=255, null=True)),
                ('product_images1', models.FileField(blank=True, max_length=255, null=True, upload_to='sample/')),
                ('product_images2', models.FileField(blank=True, max_length=255, null=True, upload_to='sample/')),
                ('product_images3', models.FileField(blank=True, max_length=255, null=True, upload_to='sample/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255, null=True)),
                ('product_name', models.CharField(max_length=255, null=True)),
                ('color', models.CharField(max_length=255, null=True)),
                ('ram', models.TextField(max_length=255, null=True)),
                ('processor', models.CharField(max_length=255, null=True)),
                ('storage', models.CharField(max_length=255, null=True)),
                ('camrear', models.CharField(max_length=255, null=True)),
                ('camfront', models.CharField(max_length=255, null=True)),
                ('price', models.CharField(max_length=255, null=True)),
                ('warranty', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(max_length=255, null=True)),
                ('display', models.TextField(max_length=255, null=True)),
                ('quantity', models.CharField(max_length=255, null=True)),
                ('product_images1', models.FileField(blank=True, max_length=255, null=True, upload_to='sample/')),
                ('product_images2', models.FileField(blank=True, max_length=255, null=True, upload_to='sample/')),
                ('product_images3', models.FileField(blank=True, max_length=255, null=True, upload_to='sample/')),
                ('product_images4', models.FileField(blank=True, max_length=255, null=True, upload_to='sample/')),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductLap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255, null=True)),
                ('product_name', models.CharField(max_length=255, null=True)),
                ('color', models.CharField(max_length=255, null=True)),
                ('ram', models.TextField(max_length=255, null=True)),
                ('processor', models.CharField(max_length=255, null=True)),
                ('storage', models.CharField(max_length=255, null=True)),
                ('price', models.CharField(max_length=255, null=True)),
                ('warranty', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(max_length=255, null=True)),
                ('quantity', models.CharField(max_length=255, null=True)),
                ('product_images1', models.FileField(blank=True, max_length=255, null=True, upload_to='sample/')),
                ('product_images2', models.FileField(blank=True, max_length=255, null=True, upload_to='sample/')),
                ('product_images3', models.FileField(blank=True, max_length=255, null=True, upload_to='sample/')),
                ('product_images4', models.FileField(blank=True, max_length=255, null=True, upload_to='sample/')),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductHeadset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255, null=True)),
                ('product_name', models.CharField(max_length=255, null=True)),
                ('battery', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(max_length=255, null=True)),
                ('price', models.CharField(max_length=255, null=True)),
                ('color', models.CharField(max_length=255, null=True)),
                ('quantity', models.CharField(max_length=255, null=True)),
                ('sound_quality', models.CharField(max_length=255, null=True)),
                ('product_images1', models.FileField(blank=True, max_length=255, null=True, upload_to='sample/')),
                ('product_images2', models.FileField(blank=True, max_length=255, null=True, upload_to='sample/')),
                ('product_images3', models.FileField(blank=True, max_length=255, null=True, upload_to='sample/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
