# Generated by Django 4.2.5 on 2023-09-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_productspeaker_productmobile_productlap_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productspeaker',
            old_name='sound_quality',
            new_name='quality',
        ),
        migrations.RemoveField(
            model_name='productheadset',
            name='sound_quality',
        ),
        migrations.AlterField(
            model_name='productmobile',
            name='product_images1',
            field=models.ImageField(null=True, upload_to='sample/'),
        ),
        migrations.AlterField(
            model_name='productmobile',
            name='product_images2',
            field=models.ImageField(null=True, upload_to='sample/'),
        ),
        migrations.AlterField(
            model_name='productmobile',
            name='product_images3',
            field=models.ImageField(null=True, upload_to='sample/'),
        ),
        migrations.AlterField(
            model_name='productmobile',
            name='product_images4',
            field=models.ImageField(null=True, upload_to='sample/'),
        ),
        migrations.AlterField(
            model_name='productspeaker',
            name='product_images1',
            field=models.ImageField(blank=True, null=True, upload_to='sample/'),
        ),
        migrations.AlterField(
            model_name='productspeaker',
            name='product_images2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='sample/'),
        ),
    ]
