# Generated by Django 4.2.5 on 2023-09-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_remove_cart_subtotal_remove_cart_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlap',
            name='stock',
            field=models.PositiveIntegerField(default=0, max_length=255),
        ),
    ]
