# Generated by Django 4.2.5 on 2023-09-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_productlap_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlap',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, max_length=255),
        ),
    ]
