# Generated by Django 4.2.5 on 2023-10-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_remove_productlap_stock_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cartstock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
