# Generated by Django 4.2.5 on 2023-10-12 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
