# Generated by Django 4.2.5 on 2023-10-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0007_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Customer'), (2, 'Seller'), (3, 'Delivery')], default=1, null=True),
        ),
    ]
